// THIS NAME MUST BE THE SAME AS IN FRONTEND CONSTANS, DON'T CHANGE IT, OR IF YOU NEED TO CHANGE, DO IT ALSO IN THE FRONTEND.
export const SESSION_COOKIE_NAME = 'NESTJS_SESSION_COOKIE';
export const SESSION_TTL = 604800;
export const COOKIE_MAX_AGE = 3600000;

export const GOOGLE_REDIRECT_URL = '/api/auth/redirect';